"""empty message

Revision ID: 273a9e170a5c
Revises: 0e9ba1e83773
Create Date: 2024-03-16 12:05:34.160967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273a9e170a5c'
down_revision = '0e9ba1e83773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, default='user'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
