"""Changed Talen table

Revision ID: 506d4a77624c
Revises: bb686bf679fb
Create Date: 2024-03-18 13:34:44.719377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506d4a77624c'
down_revision = 'bb686bf679fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docentID', sa.String(), nullable=False))
        batch_op.create_unique_constraint('docentidconst', ['docentID'])
        batch_op.create_foreign_key('foreignkeyusersdocentid', 'users', ['docentID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('docentID')

    # ### end Alembic commands ###
