"""Removed DocentID from Talen Table

Revision ID: 599e5f1b6ee6
Revises: 506d4a77624c
Create Date: 2024-03-18 13:44:07.246299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599e5f1b6ee6'
down_revision = '506d4a77624c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talen', schema=None) as batch_op:
        batch_op.drop_constraint('docentidconst', type_='unique')
        batch_op.drop_constraint('foreignkeyusersdocentid', type_='foreignkey')
        batch_op.drop_column('docentID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docentID', sa.VARCHAR(), nullable=False))
        batch_op.create_foreign_key('foreignkeyusersdocentid', 'users', ['docentID'], ['id'])
        batch_op.create_unique_constraint('docentidconst', ['docentID'])

    # ### end Alembic commands ###
