"""Change nullable in Lessen

Revision ID: 7694fbc4965d
Revises: 599e5f1b6ee6
Create Date: 2024-03-19 10:23:22.567008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7694fbc4965d'
down_revision = '599e5f1b6ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessen', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessen', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
