"""Added inschrijvingen tabel

Revision ID: 9ca48204076d
Revises: 818aad479805
Create Date: 2024-03-19 15:15:25.633463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca48204076d'
down_revision = '818aad479805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inschrijvingen',
    sa.Column('inschrijvingenID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('lessenID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lessenID'], ['lessen.lesID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('inschrijvingenID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inschrijvingen')
    # ### end Alembic commands ###
