"""Add cascading delete

Revision ID: bb686bf679fb
Revises: d9cdf3c68373
Create Date: 2024-03-17 13:05:58.373506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb686bf679fb'
down_revision = 'd9cdf3c68373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessen', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('talenID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessen', schema=None) as batch_op:
        batch_op.alter_column('talenID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
