"""Added prijs to Lessen and added default

Revision ID: e4b4da41adb8
Revises: 9ca48204076d
Create Date: 2024-03-26 10:43:48.344634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b4da41adb8'
down_revision = '9ca48204076d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prijs', sa.Integer(), nullable=False))

    with op.batch_alter_table('talen', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_talen_name'), ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('talen', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_talen_name'), type_='unique')

    with op.batch_alter_table('lessen', schema=None) as batch_op:
        batch_op.drop_column('prijs')

    # ### end Alembic commands ###
